FROM python:3.9.7-slim-buster

WORKDIR /test_task_news
VOLUME /result

COPY requirements.txt requirements.txt
COPY . .

RUN apt-get update \
    && pip3 install -r requirements.txt
    # && apt-get install xmlstarlet -y
    # && cd result
    # && xmlstarlet format result.xml

CMD ["python3", "work_dir/news_scrapper.py"]



